---
- name: Example playbook to demonstrate ansible_hostname_ vs invenory_hostname
  hosts: webserver
  gather_facts: yes

  tasks:
    - name: Display inventory_hostname
      debug:
        msg: "inventory_hostname: {{ inventory_hostname }}"
    
    - name: Display ansible_hostname
      debug:
        msg: "ansible_hostname: {{ ansible_hostname }}"