- name: Example playbook Without Ansible Vault
  hosts: localhost
  vars:
    db_username: 'admin'
    db_password: 'supersecretpassword'
  tasks:
    - name: Print the database username and password
      debug:
        msg: "Database Username: {{ db_username }}, Password: {{ db_password }}"