---
- name: Install Docker
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      # Update apt cache: Ensures that the local APT package cache is up to date.

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        name: "{{ item }}"
        state: present
        cache_valid_time: 3600
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      # Install prerequisite packages: Installs packages required for APT to use repositories over HTTPS, 
      # which is necessary for Docker's repository.

    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      # Create keyrings directory: Ensures the directory for storing GPG keys exists.

    - name: Download Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      # Download GPG key: Downloads Docker’s GPG key to /etc/apt/keyrings/docker.asc.

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
      # Add Docker repository: Configures the Docker APT repository, referencing the GPG key.

    - name: Update apt cache after adding repository
      apt:
        update_cache: yes
      # Update cache: Ensures the APT cache is updated after adding the new repository.

    - name: Install Docker and Docker Compose
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin  # Updated to use the modern Docker Compose plugin
        state: present
      # Install Docker and Docker Compose: Installs Docker packages and the Docker Compose plugin.

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check Docker service status
      command: systemctl status docker --no-pager
      register: docker_status
      changed_when: false

    - name: Print Docker service status
      debug:
        msg: "Docker service status: {{ docker_status.stdout }}"
      when: docker_status.rc == 0