---
- name: Use community.general collection on Ubuntu
  hosts: webservers
  become: yes

  tasks:
    - name: Get OS release info
      ansible.builtin.slurp:
        src: /etc/os-release
      register: os_release

    - name: Print OS info
      debug:
        msg: "OS Info: {{ os_release.content | b64decode }}"

    - name: Download content from URL
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ansible/ansible/stable-2.16/README.md"  # Using stable branch
        dest: /tmp/ansible_readme.md  # Changed destination filename
        mode: 0644
      register: download_result
      until: download_result is succeeded  # Retry if fails
      retries: 3
      delay: 2

- name: Install Docker and run Nginx container
  hosts: webservers
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx-1.1
        image: nginx
        ports:
          - "80:80"
        state: started

    - name: Verify Nginx container status
      community.docker.docker_container_info:
        name: nginx-1.1
      register: nginx_container_info

    - name: Check if Nginx container is running
      ansible.builtin.assert:
        that:
          - nginx_container_info.container.State.Status == 'running'
        success_msg: "Nginx container is running"
        fail_msg: "Nginx container is not running"

    - name: Verify connection to Nginx
      ansible.builtin.uri:
        url: "http://localhost:80"
        status_code: 200
      register: nginx_response

    - name: Print Nginx response
      debug:
        var: nginx_response